<template>
  <div class="min-h-screen">
    <!-- Hero Section -->
    <section class="bg-gradient-to-r from-indigo-600 to-purple-600 text-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24">
        <div class="text-center">
          <h1 class="text-4xl md:text-6xl font-bold mb-6">
            Master Programming with
            <span class="text-yellow-300">AI-Powered Quizzes</span>
          </h1>
          <p class="text-xl md:text-2xl mb-8 text-indigo-100">
            Enhance your coding skills with personalized quizzes generated by advanced AI
          </p>
          <div class="space-x-4">
            <router-link
              v-if="!authStore.isAuthenticated"
              to="/register"
              class="bg-yellow-400 text-gray-900 hover:bg-yellow-300 px-8 py-3 rounded-lg text-lg font-semibold transition duration-300"
            >
              Get Started Free
            </router-link>
            <router-link
              v-else
              to="/dashboard"
              class="bg-yellow-400 text-gray-900 hover:bg-yellow-300 px-8 py-3 rounded-lg text-lg font-semibold transition duration-300"
            >
              Go to Dashboard
            </router-link>
            <button class="border-2 border-white text-white hover:bg-white hover:text-indigo-600 px-8 py-3 rounded-lg text-lg font-semibold transition duration-300">
              Watch Demo
            </button>
          </div>
        </div>
      </div>
    </section>

    <!-- Features Section -->
    <section class="py-20 bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Why Choose QuizAI?
          </h2>
          <p class="text-xl text-gray-600">
            Advanced features designed to accelerate your learning journey
          </p>
        </div>

        <div class="grid md:grid-cols-3 gap-8">
          <div class="text-center p-6">
            <div class="w-16 h-16 bg-indigo-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg class="w-8 h-8 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 mb-2">AI-Generated Content</h3>
            <p class="text-gray-600">
              Dynamic quiz questions generated by advanced AI based on your learning needs and progress
            </p>
          </div>

          <div class="text-center p-6">
            <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 mb-2">Code Execution</h3>
            <p class="text-gray-600">
              Test your code in a secure sandbox environment with real-time feedback and validation
            </p>
          </div>

          <div class="text-center p-6">
            <div class="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg class="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
              </svg>
            </div>
            <h3 class="text-xl font-semibold text-gray-900 mb-2">Progress Tracking</h3>
            <p class="text-gray-600">
              Detailed analytics and insights to track your learning progress and identify areas for improvement
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Languages Section -->
    <section class="py-20 bg-gray-50">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-16">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Multiple Programming Languages
          </h2>
          <p class="text-xl text-gray-600">
            Practice and master various programming languages
          </p>
        </div>

        <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-6">
          <div v-for="language in languages" :key="language.name" class="text-center p-4 bg-white rounded-lg shadow-sm hover:shadow-md transition duration-300">
            <div class="text-3xl mb-2">{{ language.icon }}</div>
            <h3 class="font-semibold text-gray-900">{{ language.name }}</h3>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA Section -->
    <section class="bg-indigo-600 text-white py-20">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h2 class="text-3xl md:text-4xl font-bold mb-4">
          Ready to Level Up Your Coding Skills?
        </h2>
        <p class="text-xl mb-8 text-indigo-100">
          Join thousands of developers who are already improving their skills with QuizAI
        </p>
        <router-link
          v-if="!authStore.isAuthenticated"
          to="/register"
          class="bg-yellow-400 text-gray-900 hover:bg-yellow-300 px-8 py-3 rounded-lg text-lg font-semibold transition duration-300"
        >
          Start Learning Today
        </router-link>
        <router-link
          v-else
          to="/quizzes"
          class="bg-yellow-400 text-gray-900 hover:bg-yellow-300 px-8 py-3 rounded-lg text-lg font-semibold transition duration-300"
        >
          Browse Quizzes
        </router-link>
      </div>
    </section>
  </div>
</template>

<script setup>
import { useAuthStore } from '../stores/auth'

const authStore = useAuthStore()

const languages = [
  { name: 'JavaScript', icon: '🟨' },
  { name: 'Python', icon: '🐍' },
  { name: 'Java', icon: '☕' },
  { name: 'C++', icon: '⚡' },
  { name: 'HTML', icon: '🌐' },
  { name: 'CSS', icon: '🎨' },
  { name: 'SQL', icon: '🗄️' }
]
</script>
